name: Linux Package Builder

on:
  release:
    types:
      - published

jobs:
  build-packages:
    name: Build DEB/RPM Packages
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04-arm]
        include:
          - platform: ubuntu-latest
            deb_arch: amd64
            rpm_arch: x86_64
            target: x86_64-unknown-linux-gnu
          - platform: ubuntu-22.04-arm
            deb_arch: arm64
            rpm_arch: aarch64
            target: aarch64-unknown-linux-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev rubygems build-essential rpm
          sudo gem install fpm --no-document

      - name: Build binaries
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create DEB packages
        run: |
          for app in scal sdate sstat; do
            fpm -s dir -t deb \
              -n $app \
              -v ${{ github.ref_name }} \
              -a ${{ matrix.deb_arch }} \
              --maintainer "Amir Arsalan Yavari" \
              --description "$app application" \
              --package $app-${{ matrix.deb_arch }}.deb \
              ./target/${{ matrix.target }}/release/$app=/usr/bin/$app
          done

      - name: Create RPM packages
        run: |
          for app in scal sdate sstat; do
            fpm -s dir -t rpm \
              -n $app \
              -v ${{ github.ref_name }} \
              -a ${{ matrix.rpm_arch }} \
              --maintainer "Amir Arsalan Yavari" \
              --description "$app application" \
              --package $app-${{ matrix.rpm_arch }}.rpm \
              ./target/${{ matrix.target }}/release/$app=/usr/bin/$app
          done

      - name: Upload packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
